[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --filter=server --filter=db"]

[phases.build]
cmds = [
    "pnpm build --filter=server --filter=db",
    "cd packages/db && pnpm db:migrate",
]

[start]
cmd = "cd apps/server && pnpm start:prod"
