export const ADJECTIVES = ['EPIC', 'LEGENDARY', 'ELITE', 'CHAMPION', 'VICTORY']

export const TAKEN_CODES = ['RALLY-TAKEN', 'JOHN123', 'POPULAR']

export const VALID_REFERRAL_CODES = ['RALLY-FRIEND', 'WELCOME25', 'NEWUSER']

export const CODE_VALIDATION = {
  MIN_LENGTH: 3,
  MAX_LENGTH: 20,
  INVALID_CHARS_REGEX: /[^A-Z0-9-_]/,
}

export const REFERRAL_REWARDS = {
  BONUS_AMOUNT: 25,
  CURRENCY: '$',
}

export const VALIDATION_DELAYS = {
  CODE_CHECK: 1000,
  REFERRAL_CHECK: 800,
}
