const mockLobbiesData = {
  lobbies: [
    {
      id: '1',
      title: 'NBA Night Showdown',
      creatorId: '101',
      creator: { username: 'HoopsKing', avatar: '🏀', id: '101' },
      imageUrl: '/images/pfp-1.svg',
      numBets: 3,
      depositAmount: 10,
      maxParticipants: 8,
      participants: [
        {
          id: 'p1',
          userId: 'p1',
          user: { id: 'p1', username: 'Player1', avatar: '/images/pfp-1.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b1',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 25,
                actualValue: 20,
                currentValue: 20,
                athleteId: 'a1',
                athlete: {
                  name: 'LeBron James',
                  position: 'SF',
                  jerseyNumber: 6,
                  picture: '/images/pfp-1.svg',
                  team: { abbreviation: 'LAL', id: 't1' },
                },
                matchup: {
                  homeTeamId: 't1',
                  homeTeam: { abbreviation: 'LAL', id: 't1' },
                  awayTeam: { abbreviation: 'GSW', id: 't2' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Points' },
              },
            },
            {
              id: 'b2',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'resolved',
                predictedValue: 10,
                actualValue: 12,
                currentValue: 12,
                athleteId: 'a2',
                athlete: {
                  name: 'Stephen Curry',
                  position: 'PG',
                  jerseyNumber: 30,
                  picture: '/images/pfp-2.svg',
                  team: { abbreviation: 'GSW', id: 't2' },
                },
                matchup: {
                  homeTeamId: 't2',
                  homeTeam: { abbreviation: 'GSW', id: 't2' },
                  awayTeam: { abbreviation: 'LAL', id: 't1' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Assists' },
              },
            },
            {
              id: 'b3',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 8,
                actualValue: 6,
                currentValue: 6,
                athleteId: 'a3',
                athlete: {
                  name: 'Kevin Durant',
                  position: 'PF',
                  jerseyNumber: 35,
                  picture: '/images/pfp-3.svg',
                  team: { abbreviation: 'PHX', id: 't3' },
                },
                matchup: {
                  homeTeamId: 't3',
                  homeTeam: { abbreviation: 'PHX', id: 't3' },
                  awayTeam: { abbreviation: 'LAL', id: 't1' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Rebounds' },
              },
            },
          ],
        },
        {
          id: 'p2',
          userId: 'p2',
          user: { id: 'p2', username: 'Player2', avatar: '/images/pfp-2.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b4',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 8,
                actualValue: 6,
                currentValue: 6,
                athleteId: 'a4',
                athlete: {
                  name: 'Klay Thompson',
                  position: 'SG',
                  jerseyNumber: 11,
                  picture: '/images/pfp-4.svg',
                  team: { abbreviation: 'GSW', id: 't2' },
                },
                matchup: {
                  homeTeamId: 't2',
                  homeTeam: { abbreviation: 'GSW', id: 't2' },
                  awayTeam: { abbreviation: 'PHX', id: 't3' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: '3PT Made' },
              },
            },
            {
              id: 'b5',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 22,
                actualValue: 22,
                currentValue: 22,
                athleteId: 'a5',
                athlete: {
                  name: 'Giannis Antetokounmpo',
                  position: 'C',
                  jerseyNumber: 34,
                  picture: '/images/pfp-5.svg',
                  team: { abbreviation: 'MIL', id: 't4' },
                },
                matchup: {
                  homeTeamId: 't4',
                  homeTeam: { abbreviation: 'MIL', id: 't4' },
                  awayTeam: { abbreviation: 'GSW', id: 't2' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Blocks' },
              },
            },
            {
              id: 'b6',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'resolved',
                predictedValue: 12,
                actualValue: 14,
                currentValue: 14,
                athleteId: 'a6',
                athlete: {
                  name: 'Joel Embiid',
                  position: 'C',
                  jerseyNumber: 21,
                  picture: '/images/pfp-6.svg',
                  team: { abbreviation: 'PHI', id: 't5' },
                },
                matchup: {
                  homeTeamId: 't5',
                  homeTeam: { abbreviation: 'PHI', id: 't5' },
                  awayTeam: { abbreviation: 'LAL', id: 't1' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Turnovers' },
              },
            },
          ],
        },
        {
          id: 'p3',
          userId: 'p3',
          user: { id: 'p3', username: 'Player3', avatar: '/images/pfp-3.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b7',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 15,
                actualValue: 13,
                currentValue: 13,
                athleteId: 'a7',
                athlete: {
                  name: 'Jayson Tatum',
                  position: 'SF',
                  jerseyNumber: 0,
                  picture: '/images/pfp-7.svg',
                  team: { abbreviation: 'BOS', id: 't6' },
                },
                matchup: {
                  homeTeamId: 't6',
                  homeTeam: { abbreviation: 'BOS', id: 't6' },
                  awayTeam: { abbreviation: 'MIL', id: 't4' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Steals' },
              },
            },
            {
              id: 'b8',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 9,
                actualValue: 7,
                currentValue: 7,
                athleteId: 'a8',
                athlete: {
                  name: 'Jimmy Butler',
                  position: 'SG',
                  jerseyNumber: 22,
                  picture: '/images/pfp-8.svg',
                  team: { abbreviation: 'MIA', id: 't7' },
                },
                matchup: {
                  homeTeamId: 't7',
                  homeTeam: { abbreviation: 'MIA', id: 't7' },
                  awayTeam: { abbreviation: 'BOS', id: 't6' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Free Throws' },
              },
            },
            {
              id: 'b9',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 20,
                actualValue: 20,
                currentValue: 20,
                athleteId: 'a9',
                athlete: {
                  name: 'Nikola Jokic',
                  position: 'C',
                  jerseyNumber: 15,
                  picture: '/images/pfp-9.svg',
                  team: { abbreviation: 'DEN', id: 't8' },
                },
                matchup: {
                  homeTeamId: 't8',
                  homeTeam: { abbreviation: 'DEN', id: 't8' },
                  awayTeam: { abbreviation: 'MIA', id: 't7' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Double Doubles' },
              },
            },
          ],
        },
        {
          id: 'p4',
          userId: 'p4',
          user: { id: 'p4', username: 'Player4', avatar: '/images/pfp-4.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b10',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'resolved',
                predictedValue: 12,
                actualValue: 14,
                currentValue: 14,
                athleteId: 'a10',
                athlete: {
                  name: 'Zion Williamson',
                  position: 'PF',
                  jerseyNumber: 1,
                  picture: '/images/pfp-10.svg',
                  team: { abbreviation: 'NOP', id: 't9' },
                },
                matchup: {
                  homeTeamId: 't9',
                  homeTeam: { abbreviation: 'NOP', id: 't9' },
                  awayTeam: { abbreviation: 'PHI', id: 't5' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Personal Fouls' },
              },
            },
            {
              id: 'b11',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 16,
                actualValue: 16,
                currentValue: 16,
                athleteId: 'a11',
                athlete: {
                  name: 'Luka Doncic',
                  position: 'PG',
                  jerseyNumber: 77,
                  picture: '/images/pfp-11.svg',
                  team: { abbreviation: 'DAL', id: 't10' },
                },
                matchup: {
                  homeTeamId: 't10',
                  homeTeam: { abbreviation: 'DAL', id: 't10' },
                  awayTeam: { abbreviation: 'NOP', id: 't9' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Triple Doubles' },
              },
            },
            {
              id: 'b12',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 19,
                actualValue: 19,
                currentValue: 19,
                athleteId: 'a12',
                athlete: {
                  name: 'Devin Booker',
                  position: 'SG',
                  jerseyNumber: 1,
                  picture: '/images/pfp-12.svg',
                  team: { abbreviation: 'PHX', id: 't3' },
                },
                matchup: {
                  homeTeamId: 't3',
                  homeTeam: { abbreviation: 'PHX', id: 't3' },
                  awayTeam: { abbreviation: 'DAL', id: 't10' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Field Goals' },
              },
            },
          ],
        },
      ],
      createdAt: new Date().toISOString(),
      gameCode: 'CODE1',
      prizePool: 80,
      status: 'open',
      legs: [],
      winners: [],
      chat: [],
      stats: {},
    },
    {
      id: '2',
      title: 'Premier League Derby',
      creatorId: '102',
      creator: { username: 'FootyFan', avatar: '⚽', id: '102' },
      imageUrl: '/images/pfp-2.svg',
      numBets: 5,
      depositAmount: 20,
      maxParticipants: 10,
      participants: [
        {
          id: 'p5',
          userId: 'p5',
          user: { id: 'p5', username: 'Player5', avatar: '/images/pfp-1.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b13',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 2,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a13',
                athlete: {
                  name: 'Erling Haaland',
                  position: 'ST',
                  jerseyNumber: 9,
                  picture: '/images/pfp-5.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Goals' },
              },
            },
            {
              id: 'b14',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a14',
                athlete: {
                  name: 'Mohamed Salah',
                  position: 'RW',
                  jerseyNumber: 11,
                  picture: '/images/pfp-6.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Assists' },
              },
            },
            {
              id: 'b15',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 3,
                actualValue: 3,
                currentValue: 3,
                athleteId: 'a15',
                athlete: {
                  name: 'Kevin De Bruyne',
                  position: 'CM',
                  jerseyNumber: 17,
                  picture: '/images/pfp-7.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Key Passes' },
              },
            },
            {
              id: 'b15a',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 2,
                actualValue: 1,
                currentValue: 1,
                athleteId: 'a15a',
                athlete: {
                  name: 'John Stones',
                  position: 'CB',
                  jerseyNumber: 5,
                  picture: '/images/pfp-8.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Headers Won' },
              },
            },
            {
              id: 'b15b',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a15b',
                athlete: {
                  name: 'James Milner',
                  position: 'CM',
                  jerseyNumber: 7,
                  picture: '/images/pfp-9.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Red Cards' },
              },
            },
          ],
        },
        {
          id: 'p6',
          userId: 'p6',
          user: { id: 'p6', username: 'Player6', avatar: '/images/pfp-2.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b16',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 0,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a16',
                athlete: {
                  name: 'Virgil van Dijk',
                  position: 'CB',
                  jerseyNumber: 4,
                  picture: '/images/pfp-8.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Yellow Cards' },
              },
            },
            {
              id: 'b17',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 5,
                actualValue: 3,
                currentValue: 3,
                athleteId: 'a17',
                athlete: {
                  name: 'Phil Foden',
                  position: 'LW',
                  jerseyNumber: 47,
                  picture: '/images/pfp-9.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Shots' },
              },
            },
            {
              id: 'b18',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 2,
                actualValue: 1,
                currentValue: 1,
                athleteId: 'a18',
                athlete: {
                  name: 'Alisson Becker',
                  position: 'GK',
                  jerseyNumber: 1,
                  picture: '/images/pfp-10.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Saves' },
              },
            },
            {
              id: 'b18a',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 1,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a18a',
                athlete: {
                  name: 'Rodri',
                  position: 'CDM',
                  jerseyNumber: 16,
                  picture: '/images/pfp-11.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Interceptions' },
              },
            },
            {
              id: 'b18b',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 0,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a18b',
                athlete: {
                  name: 'Andy Robertson',
                  position: 'LB',
                  jerseyNumber: 26,
                  picture: '/images/pfp-12.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Throw-ins' },
              },
            },
          ],
        },
        {
          id: 'p7',
          userId: 'p7',
          user: { id: 'p7', username: 'Player7', avatar: '/images/pfp-3.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b19',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 1,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a19',
                athlete: {
                  name: 'Andrew Robertson',
                  position: 'LB',
                  jerseyNumber: 26,
                  picture: '/images/pfp-11.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Crosses' },
              },
            },
            {
              id: 'b20',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 2,
                actualValue: 1,
                currentValue: 1,
                athleteId: 'a20',
                athlete: {
                  name: 'Jack Grealish',
                  position: 'LW',
                  jerseyNumber: 10,
                  picture: '/images/pfp-12.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Dribbles' },
              },
            },
            {
              id: 'b21',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 4,
                actualValue: 4,
                currentValue: 4,
                athleteId: 'a21',
                athlete: {
                  name: 'Bernardo Silva',
                  position: 'CM',
                  jerseyNumber: 20,
                  picture: '/images/pfp-13.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Tackles' },
              },
            },
            {
              id: 'b21a',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 2,
                actualValue: 1,
                currentValue: 1,
                athleteId: 'a21a',
                athlete: {
                  name: 'Ilkay Gundogan',
                  position: 'CM',
                  jerseyNumber: 8,
                  picture: '/images/pfp-14.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Passes Completed' },
              },
            },
            {
              id: 'b21b',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a21b',
                athlete: {
                  name: 'Diogo Jota',
                  position: 'CF',
                  jerseyNumber: 20,
                  picture: '/images/pfp-15.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Goals' },
              },
            },
          ],
        },
        {
          id: 'p8',
          userId: 'p8',
          user: { id: 'p8', username: 'Player8', avatar: '/images/pfp-4.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b22',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a22',
                athlete: {
                  name: 'Ederson',
                  position: 'GK',
                  jerseyNumber: 31,
                  picture: '/images/pfp-14.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Clean Sheets' },
              },
            },
            {
              id: 'b23',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 2,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a23',
                athlete: {
                  name: 'Trent Alexander-Arnold',
                  position: 'RB',
                  jerseyNumber: 66,
                  picture: '/images/pfp-15.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Interceptions' },
              },
            },
            {
              id: 'b24',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a24',
                athlete: {
                  name: 'Fabinho',
                  position: 'CDM',
                  jerseyNumber: 3,
                  picture: '/images/pfp-16.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Fouls' },
              },
            },
            {
              id: 'b24a',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 1,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a24a',
                athlete: {
                  name: 'Joel Matip',
                  position: 'CB',
                  jerseyNumber: 32,
                  picture: '/images/pfp-17.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Headers Won' },
              },
            },
            {
              id: 'b24b',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 0,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a24b',
                athlete: {
                  name: 'Nathan Ake',
                  position: 'CB',
                  jerseyNumber: 6,
                  picture: '/images/pfp-18.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Tackles' },
              },
            },
          ],
        },
        {
          id: 'p9',
          userId: 'p9',
          user: { id: 'p9', username: 'Player9', avatar: '/images/pfp-5.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b25',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 2,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a25',
                athlete: {
                  name: 'Riyad Mahrez',
                  position: 'RW',
                  jerseyNumber: 26,
                  picture: '/images/pfp-17.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Corners' },
              },
            },
            {
              id: 'b26',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a26',
                athlete: {
                  name: 'Jordan Henderson',
                  position: 'CM',
                  jerseyNumber: 14,
                  picture: '/images/pfp-18.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Offsides' },
              },
            },
            {
              id: 'b27',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 3,
                actualValue: 3,
                currentValue: 3,
                athleteId: 'a27',
                athlete: {
                  name: 'Aymeric Laporte',
                  position: 'CB',
                  jerseyNumber: 14,
                  picture: '/images/pfp-19.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Clearances' },
              },
            },
            {
              id: 'b27a',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 1,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a27a',
                athlete: {
                  name: 'Curtis Jones',
                  position: 'CM',
                  jerseyNumber: 17,
                  picture: '/images/pfp-20.svg',
                  team: { abbreviation: 'LIV', id: 't12' },
                },
                matchup: {
                  homeTeamId: 't12',
                  homeTeam: { abbreviation: 'LIV', id: 't12' },
                  awayTeam: { abbreviation: 'MCI', id: 't11' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Shots on Target' },
              },
            },
            {
              id: 'b27b',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 2,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a27b',
                athlete: {
                  name: 'Gabriel Jesus',
                  position: 'CF',
                  jerseyNumber: 9,
                  picture: '/images/pfp-21.svg',
                  team: { abbreviation: 'MCI', id: 't11' },
                },
                matchup: {
                  homeTeamId: 't11',
                  homeTeam: { abbreviation: 'MCI', id: 't11' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Goals' },
              },
            },
          ],
        },
        {
          id: 'p10',
          userId: 'p10',
          user: { id: 'p10', username: 'Player10', avatar: '/images/pfp-6.svg' },
          joinedAt: new Date().toISOString(),
          bets: [
            {
              id: 'b28',
              predictedDirection: 'under',
              isCorrect: false,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a28',
                athlete: {
                  name: 'Edouard Mendy',
                  position: 'GK',
                  jerseyNumber: 16,
                  picture: '/images/pfp-20.svg',
                  team: { abbreviation: 'CHE', id: 't13' },
                },
                matchup: {
                  homeTeamId: 't13',
                  homeTeam: { abbreviation: 'CHE', id: 't13' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Penalties Saved' },
              },
            },
            {
              id: 'b29',
              predictedDirection: 'over',
              isCorrect: true,
              line: {
                status: 'locked',
                predictedValue: 2,
                actualValue: 2,
                currentValue: 2,
                athleteId: 'a29',
                athlete: {
                  name: 'Mason Mount',
                  position: 'CAM',
                  jerseyNumber: 19,
                  picture: '/images/pfp-21.svg',
                  team: { abbreviation: 'CHE', id: 't13' },
                },
                matchup: {
                  homeTeamId: 't13',
                  homeTeam: { abbreviation: 'CHE', id: 't13' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Chances Created' },
              },
            },
            {
              id: 'b30',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 1,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a30',
                athlete: {
                  name: 'Thiago Silva',
                  position: 'CB',
                  jerseyNumber: 6,
                  picture: '/images/pfp-22.svg',
                  team: { abbreviation: 'CHE', id: 't13' },
                },
                matchup: {
                  homeTeamId: 't13',
                  homeTeam: { abbreviation: 'CHE', id: 't13' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Blocks' },
              },
            },
            {
              id: 'b30a',
              predictedDirection: 'over',
              isCorrect: false,
              line: {
                status: 'locked',
                predictedValue: 2,
                actualValue: 1,
                currentValue: 1,
                athleteId: 'a30a',
                athlete: {
                  name: 'Ben Chilwell',
                  position: 'LB',
                  jerseyNumber: 21,
                  picture: '/images/pfp-23.svg',
                  team: { abbreviation: 'CHE', id: 't13' },
                },
                matchup: {
                  homeTeamId: 't13',
                  homeTeam: { abbreviation: 'CHE', id: 't13' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Crosses' },
              },
            },
            {
              id: 'b30b',
              predictedDirection: 'under',
              isCorrect: true,
              line: {
                status: 'resolved',
                predictedValue: 0,
                actualValue: 0,
                currentValue: 0,
                athleteId: 'a30b',
                athlete: {
                  name: 'Hakim Ziyech',
                  position: 'RW',
                  jerseyNumber: 22,
                  picture: '/images/pfp-24.svg',
                  team: { abbreviation: 'CHE', id: 't13' },
                },
                matchup: {
                  homeTeamId: 't13',
                  homeTeam: { abbreviation: 'CHE', id: 't13' },
                  awayTeam: { abbreviation: 'LIV', id: 't12' },
                  startsAt: new Date().toISOString(),
                },
                stat: { displayName: 'Dribbles' },
              },
            },
          ],
        },
      ],
      createdAt: new Date().toISOString(),
      gameCode: 'CODE2',
      prizePool: 200,
      status: 'open',
      legs: [],
      winners: [],
      chat: [],
      stats: {},
    },
  ],
}

export default mockLobbiesData
